### ISSUE TITLE
Safari 14.0 or earlier: no space between pills

### ISSUE THREAD

**Issue by masakudamatsu** [masakudamatsu/masakudamatsu.dev#24]
With iOS 14.0 or earlier, no space is rendered between pills (both vertically and horizontally)

**Comment by masakudamatsu** [comment]
## Problem

Safari 14.0 or earlier does not suppor `column-gap` and `row-gap` for flexbox ([Can I Use?](https://caniuse.com/mdn-css_properties_column-gap_flex_context)).

**Comment by masakudamatsu** [comment]
## Solution

Following the suggestion by [Zadiki (2023)](https://stackoverflow.com/questions/65452057/flexbox-gap-workaround-for-safari#comment132587563_67133945), the following code replicates `column-gap` and `row-gap` with flexbox:
```css
.pill-container {
  /* Remove the margin created by the last row of pills */
  margin-bottom: calc(-1 * var(--column-gap));
  /* Remove the margin created by the last pill in each row */
  margin-right: calc(-1 * var(--row-gap));
}
.pill-container > .pill {
  margin-bottom: var(--row-gap);
  margin-right: var(--column-gap);
}
```

Feature detection for `gap` with flexbox requires JavaScript, according to [Shadeed (2020)](https://ishadeed.com/article/flexbox-gap/). That's too much. Since the above CSS rules work for every browser, we just use it and ditch `gap` with flexbox.
